// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtaQPf1sIF4AioDLll1naft6wfkjf1Pjk',
    appId: '1:333820794593:web:6bff234e8f246361b589a0',
    messagingSenderId: '333820794593',
    projectId: 'skillsync-07',
    authDomain: 'skillsync-07.firebaseapp.com',
    storageBucket: 'skillsync-07.firebasestorage.app',
    measurementId: 'G-1ZRQPZSTYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAfd4TU4limRgUfNez5GUayL-a_QRrCvg',
    appId: '1:333820794593:android:51f36443586002c6b589a0',
    messagingSenderId: '333820794593',
    projectId: 'skillsync-07',
    storageBucket: 'skillsync-07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALo9-shA8gv2hym_oatWbeoRmOioyjN5s',
    appId: '1:333820794593:ios:cbfe9c3aff645d77b589a0',
    messagingSenderId: '333820794593',
    projectId: 'skillsync-07',
    storageBucket: 'skillsync-07.firebasestorage.app',
    iosBundleId: 'com.example.sharebill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALo9-shA8gv2hym_oatWbeoRmOioyjN5s',
    appId: '1:333820794593:ios:cbfe9c3aff645d77b589a0',
    messagingSenderId: '333820794593',
    projectId: 'skillsync-07',
    storageBucket: 'skillsync-07.firebasestorage.app',
    iosBundleId: 'com.example.sharebill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtaQPf1sIF4AioDLll1naft6wfkjf1Pjk',
    appId: '1:333820794593:web:c4a4465bdabff767b589a0',
    messagingSenderId: '333820794593',
    projectId: 'skillsync-07',
    authDomain: 'skillsync-07.firebaseapp.com',
    storageBucket: 'skillsync-07.firebasestorage.app',
    measurementId: 'G-RQTB3GHHCT',
  );
}
